print("Welcome to python programming")
print(5+8)
print("4+9")
print("My name is Nicol Wendy")
print("I am 20 years old.")
print("My hobby is listening to music and watching movies.")
print("I study Web development at Emobilis Training Institute.")
print("I love this course because its a tech course and it can help me earn my income in the future.")
print("Through this cause I can start my own business or even be employed in a tech based workplace.")
print("So far we have learnt about html,css,javascript,bootstrap and currently we are learning Python.")
print("Learning at Emoilis is through a scholarship by CRS and Safaricom with their Wezesha Vijana.")
print("go far away")